// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMLZxC1OCT5ThFssbZkOorh57cRH34mVE',
    appId: '1:399074657415:web:ae881a7397197da597e422',
    messagingSenderId: '399074657415',
    projectId: 'projeto-100-dias-thss',
    authDomain: 'projeto-100-dias-thss.firebaseapp.com',
    storageBucket: 'projeto-100-dias-thss.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-VPZb0FhbEyQWknhU3_PZSIfz0v1GIHE',
    appId: '1:399074657415:android:145607670f5ebf4197e422',
    messagingSenderId: '399074657415',
    projectId: 'projeto-100-dias-thss',
    storageBucket: 'projeto-100-dias-thss.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfW3gwvaeToIyyUyX6VZsJXECgcGRu55s',
    appId: '1:399074657415:ios:d4716b99ea5b502a97e422',
    messagingSenderId: '399074657415',
    projectId: 'projeto-100-dias-thss',
    storageBucket: 'projeto-100-dias-thss.firebasestorage.app',
    iosBundleId: 'com.example.segredo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfW3gwvaeToIyyUyX6VZsJXECgcGRu55s',
    appId: '1:399074657415:ios:d4716b99ea5b502a97e422',
    messagingSenderId: '399074657415',
    projectId: 'projeto-100-dias-thss',
    storageBucket: 'projeto-100-dias-thss.firebasestorage.app',
    iosBundleId: 'com.example.segredo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMLZxC1OCT5ThFssbZkOorh57cRH34mVE',
    appId: '1:399074657415:web:9d3ad81f1970168297e422',
    messagingSenderId: '399074657415',
    projectId: 'projeto-100-dias-thss',
    authDomain: 'projeto-100-dias-thss.firebaseapp.com',
    storageBucket: 'projeto-100-dias-thss.firebasestorage.app',
  );
}
